### ISSUE TITLE
Catkinzing

### ISSUE THREAD

**Issue by bit-pirate** [pal-robotics/reem_teleop#13]
In the middle of doing so, I realised an important requirement for Catkin:
You can only catkinise a package, if all dependencies have been catkinised already!

DOH!

Biggest problem for us is arm_navigation (kinematics_msgs, arm_navigation_msgs, planning_environment). Since arm_navigation is deprecated, they probably won't put any effort in catkinising it.

Have to think about how we can solve this issue ...

**Comment by adolfo-rt** [comment]
I don't think arm_navigation will get catkinized. Why do you need the teleop catkinized?, because the robosem packages are already wet?

**Comment by bit-pirate** [comment]
> because the robosem packages are already wet?

Correct.

I thought about this issue last night and came up with this proposal:
I won't change reem_teleop_coordinator and will comment it out. For Robosem I don't need self-collision checking, since it can't self-collide. So I will add a robosem_teleop_coordinator with much less dependencies.
Once you guys move forward - I guess (and recommend) that will be Hydro - MoveIt hopefully will finally be released and we can reimplement the reem_teleop_coordinator with its self-collision checking based on MoveIt and catkinize it.

**Comment by bit-pirate** [comment]
This is obsolete now. Starting from Hydro (hydro-devel branch) everything is catkinized.

However, motion retargeting for REEM still needs to be re-implemented, see https://github.com/pal-robotics/reem_teleop/issues/21.
