### ISSUE TITLE
possbile bug in motion adaption

### ISSUE THREAD

**Issue by bit-pirate** [pal-robotics/reem_teleop#17]
Just found this conditional in adapt_transforms.cpp -> adaptElbows(), which is only applied to the left arm.

```
  if(l_elbow_extended_ == true)
    tf_l_elbow_hand_.setOrigin(tf::Vector3(robot_lower_arm_length_, 0.0, 0.0));  
```

Looks like this has been missed when applying a change.

**Comment by bit-pirate** [comment]
It has been there since the first commit. So, this change should either be made for both elbows or not at all.

**Comment by adolfo-rt** [comment]
I leave it up to you to determine if it should go or be applied to both arms. You're the author so you should know best.

**Comment by bit-pirate** [comment]
True. This issue was more a reminder to myself. Those lines of code have been removed already somewhere in my my commits in the reem_teleop-1.0 branch.
