### ISSUE TITLE
releases

### ISSUE THREAD

**Issue by bit-pirate** [pal-robotics/reem_teleop#2]
How will we handle the different release (diamondback, eletric, fuerte, ...)? Will we create a branch for each release?

**Comment by bit-pirate** [comment]
I set up a branch, which while house the changes needed to run the stack under Electric.

**Comment by adolfo-rt** [comment]
I believe it is standard practice to have one branch per ROS distro. I think "electric" is the usual practice instead of "ros-electric", or other names. I like the idea of organizing code distro-wise.

Thanks for the initiative.
